version: "3"
services:
  server:
    image: node-server
    container_name: node-app
    build: .
    ports:
      - 5000:5000
  db:
    image: postgres
    container_name: postgres-db
    ports: -"5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=node-db
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
